### PR TITLE
add ora2pg tool

### PR DESCRIPTION
**Pull request by olshevskiy87**

### CODE REVIEW

**Comment by olshevskiy87** [comment]
I will rebase this commit after https://github.com/dhamaniasad/awesome-postgres/pull/107

**Comment by olshevskiy87** [comment]
will rebase this branch after PR #108

**Comment by olshevskiy87** [comment]
@dhamaniasad now it's (finally!) ready :)

**Comment by dhamaniasad** [comment]
Thanks!

**Pull request merged**
