### PR TITLE
Add Wagon to GUI list

### PR DESCRIPTION
**Pull request by kwent**
- https://www.wagonhq.com

### CODE REVIEW

**Comment by donwb** [comment]
:+1: for Wagon

**Comment by lfittl** [comment]
@kwent +1, Wagon is a great product!

Could you rebase your PR to the latest master?

:bow:

**Comment by kwent** [comment]
@lfittl Done !

**Comment by lfittl** [comment]
@kwent It looks like the rebase (re-)added some unrelated commits, maybe this is the same problem as we've had in https://github.com/dhamaniasad/awesome-postgres/pull/32#issuecomment-194794080

Could you try rebasing again and see if you can make the commits (and diff) appear correctly here?

Alternatively happy to quickly make the change myself, whatever you prefer :)

**Pull request closed without merging**
