### PR TITLE
add pgbouncer

### PR DESCRIPTION
**Pull request by kfirshay**

### CODE REVIEW

**Comment by Paxa** [comment]
:+1: pgbouncer is nice

**Comment by lfittl** [comment]
@kfirshay Thanks for your contribution, agreed that PgBouncer is missing :)

Could you rebase to the latest master?

**Comment by kfirshay** [comment]
@lfittl done

**Comment by lfittl** [comment]
@kfirshay Looks like this ended up being a merge commit, I've cherry-picked your commit instead (https://github.com/dhamaniasad/awesome-postgres/commit/68fd2d9a85cd8ac50c3251af7cb1bea90b809edf)

Thanks again for thinking of pgbouncer, and don't hesitate to add other great resources/tools :)

**Comment by kfirshay** [comment]
cool thanks, kind of wonder what I did wrong, here are the steps I took to "rebase to the latest master" -

- git remote add awesome-postgres git@github.com:dhamaniasad/awesome-postgres.git
- git fetch awesome-postures
- git rebase awesome-postgres/master
- solve the conflict
- git add .
- git commit -m 'rebase against latest master'
- git rebase --continue
- git pull

**Comment by lfittl** [comment]
@kfirshay I think it might have been the commit before the `git rebase --continue` - as far as I know, you just need to add the conflicting files, and then run the continue command.

**Comment by kfirshay** [comment]
Oh yeah, my bad.

**Pull request closed without merging**
