### PR TITLE
Add ScaffoldHub

### PR DESCRIPTION
**Pull request by felipepastorelima**
Generate fullstack PostgreSQL apps with Angular, Vue or React.

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Hi @felipepastorelima ,

Thanks for the contribution! I'm not sure this is a good fit for this repository as it's designed for serverless apps and not really a tool for Postgres. Also I was not able to try it out as there isn't a free demo. 

Can you provide more information about this service and why it should be included in this list?

**Comment by felipepastorelima** [comment]
Hi @dhamaniasad, 

The tool uses PostgreSQL as the database for all the scaffolds as shown on those links:
https://youtu.be/D61NL97AH7k?t=414
https://youtu.be/VJ5S3yEvFjw?t=375
https://youtu.be/D61NL97AH7k?t=431

But I understand your point, this repository is for dedicated PostgreSQL tools and ScaffoldHub is more of a general tool..

Thanks for analysing the PR

**Comment by dhamaniasad** [comment]
Hi @felipepastorelima ,

We have included PaaS providers and admin GUIs in the list, so I think there's a chance this might also be useful. I'd need to be able to try out the service to be sure, so is it possible for you to get me a test account?

**Comment by felipepastorelima** [comment]
Yes, no problem.. I added some credits to your account.
Thanks

**Comment by dhamaniasad** [comment]
Hi @felipepastorelima ,

I just checked out your service, it's pretty neat! And it's _kinda_ somewhere along the lines of Hasura, so I think we can include it in the list. Cheers!

**Pull request merged**
