### PR TITLE
Rename Timescale to TimescaleDB

### PR DESCRIPTION
**Pull request by binakot**
Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244

### CODE REVIEW

**Comment by binakot** [comment]
@dhamaniasad Hello. Will you merge this PR?

**Comment by dhamaniasad** [comment]
Hi @binakot ,

Looks to me like they still call themselves timescale?

**Comment by binakot** [comment]
> Hi @binakot ,
> 
> Looks to me like they still call themselves timescale?

Yeah, but the official name is TimescaleDB. This is the name of extension when you install it. And you can check this page https://www.timescale.com/about and readme https://github.com/timescale/timescaledb/blob/master/README.md

**Comment by binakot** [comment]
> > Hi @binakot ,
> > Looks to me like they still call themselves timescale?
> 
> Yeah, but the official name is TimescaleDB. This is the name of extension when you install it. And you can check this page https://www.timescale.com/about and readme https://github.com/timescale/timescaledb/blob/master/README.md

What do you think? Are you agree with me?

**Comment by dhamaniasad** [comment]
@binakot Sorry for the delay, I've merged it now.

**Pull request merged**
