### PR TITLE
add pg-differ to the Utilities section

### PR DESCRIPTION
**Pull request by multum**
Node.js module for easy synchronization of postgres tables with models (json-schemas).
Migration alternative.
Tested on a real projects.
Thanks!

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Hey @av-dev! 

I'd like to hear a bit more about how you've used this in real life projects and for how long. 

At this point, since the repository is only 4 days old, I'm not sure it can be included just yet.

**Comment by av-dev** [comment]
Hi @dhamaniasad. Yes, you may be right The utility is too young to be included in this list. It was used on two projects for 2-3 months. The module was all this time on a closed npm registry

**Comment by av-dev** [comment]
Hey @dhamaniasad!
About 9 months have passed since the opening of the pull request. Maybe you can review or close it.
Have a nice day;)

**Comment by dhamaniasad** [comment]
Hi Andrey,

Definitely, I'll look into it later today. Thank you for your patience and
for your contributions to the Postgres ecosystem!

**Pull request merged**
