### PR TITLE
Add Presto PostgreSQL connector

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
@dhamaniasad can you please take a look?

**Comment by dhamaniasad** [comment]
Can this fit under one of the existing categories?

**Comment by findepi** [comment]
I didn't find the fit, hence i added a new one, but I am open to your suggestion. Please advise.

**Comment by findepi** [comment]
@dhamaniasad can you please suggest where this would fit best?

**Pull request closed without merging**
