### PR TITLE
add Telegraf A postgres metric recovery

### PR DESCRIPTION
**Pull request by arthtux**

### CODE REVIEW

**Comment by lfittl** [comment]
@arthtux Thanks for the PR!

I'm not sure I understand "postgres metric recovery" - what exactly does that mean / what does Telegraf do with/for Postgres?

**Comment by arthtux** [comment]
hi, 

telegraf recovery the metric and send the metric in database. 
after you can plug the database on the analyser of metric for the alert. 
you can see the metric retrieve here: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/postgresql

**Comment by dhamaniasad** [comment]
@arthtux Does this offer any Postgres specific benefits over [PgHero](https://github.com/ankane/pghero)?

**Comment by dhamaniasad** [comment]
I am going to go ahead and close this PR.

**Pull request closed without merging**
