### PR TITLE
Add TimescaleDB Tune to optimization section

### PR DESCRIPTION
**Pull request by binakot**
Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244

Issue #236

### CODE REVIEW

**Comment by binakot** [comment]
@dhamaniasad Hello. Will you merge this PR and what's wrong with travis ci?

**Comment by mchristofides** [comment]
> what's wrong with travis ci?

@binakot it seems to be complaining about https://zaiste.net/postgresql_primer_for_busy_people/ being down (521). I had the same issue in #247 but got lucky that the site came up so I could close and reopen.

@dhamaniasad Given that site is down again now, it might be sensible to remove from the repo, I'd be happy to send in a quick PR if so.

**Comment by dhamaniasad** [comment]
@mchristofides I've pinged @zaiste on another thread about this, we'll wait for a response. PR is welcome though, we can either replace it with a wayback machine link, or remove it, if its not coming back online.

**Comment by dhamaniasad** [comment]
Hi @binakot,

Thanks for the contribution. This looks good, but before I merge, I want to know whether this is stable software, because the latest version is `0.6.0` which seems alpha / beta stage to me.

**Comment by binakot** [comment]
> Hi @binakot,
> 
> Thanks for the contribution. This looks good, but before I merge, I want to know whether this is stable software, because the latest version is `0.6.0` which seems alpha / beta stage to me.

Hello. Yeah, it hasn't release, but it's stable. I'm using it to configure my postgres on stag/prod env. And the most important that TimescaleDB recommends it in docs https://docs.timescale.com/v1.3/getting-started/configuring

**Comment by binakot** [comment]
> > Hi @binakot,
> > Thanks for the contribution. This looks good, but before I merge, I want to know whether this is stable software, because the latest version is `0.6.0` which seems alpha / beta stage to me.
> 
> Hello. Yeah, it hasn't release, but it's stable. I'm using it to configure my postgres on stag/prod env. And the most important that TimescaleDB recommends it in docs https://docs.timescale.com/v1.3/getting-started/configuring

What do you say? Is it enough to merge this one?

**Comment by binakot** [comment]
Also additional link https://blog.timescale.com/better-database-performance-using-timescaledb-tune-fbd7ae7016fa/

**Comment by binakot** [comment]
And the last one of my PRs, @dhamaniasad :)

**Pull request merged**
