### PR TITLE
add Pomm to the list of language bindings

### PR DESCRIPTION
**Pull request by chanmix51**
Pomm is a PHP library on top of the PHP’s low level Postgres API. It provides on the fly type conversion offering a way to leverage SQL object oriented queries.

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Thanks!

**Comment by m6w6** [comment]
Which actually is not a "language-binding" (like ext/pgsql, ext/pdo_pgsql or ext/pq) but a library on top of a language binding.

**Comment by chanmix51** [comment]
@m6w6 I am happy to *meet* you :smile: we had a look at your ext/pq library during the French PHP forum and it looks very good. We want to try to use it with Pomm to compare performances and features like COPY.

Aside of that, you have got a point here, Pomm is a third part library dedicated to using Postgresql with PHP and not a language binding.

**Comment by dhamaniasad** [comment]
Should this merge be reverted in that case? Or perhaps a new section could be added for higher-level libraries?

**Comment by chanmix51** [comment]
As far as I am concerned, even though it is not a language binding, I feel Pomm has its place in this list because it is dedicated to Postgresql only and pomm-project promotes the use of Postgres in the PHP community.

**Comment by m6w6** [comment]
I think a new section for libraries explicitly dedicated to PostgreSQL makes sense, yes.

@chanmix51 Don't hesitate do contact me, when you come around looking deeper into ext/pq; I'd be happy to help.

**Pull request merged**
