### PR TITLE
Add Nancy CLI by Postgres.ai team

### PR DESCRIPTION
**Pull request by binakot**
Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244

### CODE REVIEW

**Comment by binakot** [comment]
@dhamaniasad Hello. Will you merge this PR?

**Comment by dhamaniasad** [comment]
Hi @binakot,

Thanks for the contribution. Can you provide a sample of the output generated by this tool?

**Comment by binakot** [comment]
> Hi @binakot,
> 
> Thanks for the contribution. Can you provide a sample of the output generated by this tool?

Okay. This is the slides of talk of nancy's maintainer https://www.slideshare.net/samokhvalov/nancy-cli-automated-database-experiements. Here you can find example output https://gitlab.com/postgres-ai/nancy/issues/194

**Comment by binakot** [comment]
> > Hi @binakot,
> > Thanks for the contribution. Can you provide a sample of the output generated by this tool?
> 
> Okay. This is the slides of talk by nancy's maintainer @NikolayS https://www.slideshare.net/samokhvalov/nancy-cli-automated-database-experiements. Here you can find example output https://gitlab.com/postgres-ai/nancy/issues/194

Is it enough, @dhamaniasad?

**Comment by binakot** [comment]
Any updates? @dhamaniasad

**Comment by dhamaniasad** [comment]
Thank you @binakot, merged.

**Pull request merged**
