### PR TITLE
Add pg_back

### PR DESCRIPTION
**Pull request by anayrat**

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Is the link correct?

**Comment by anayrat** [comment]
Sorry, fixed with d19e592

**Comment by anayrat** [comment]
Any news?

**Comment by cbbrowne** [comment]
It's somewhat liked...  <https://twitter.com/postgresmen/status/776141633389629440>

It's reasonably likable.  Sponsored by Dalibo, who seem pretty likable.  It's a nice wrapper for pg_dump.

I'd buy it being an OK choice.

**Pull request merged**
