### PR TITLE
More tools...

### PR DESCRIPTION
**Pull request by cbbrowne**

### CODE REVIEW

**Comment by cbbrowne** [comment]
pgcmp, sqitch, skytools

**Comment by cbbrowne** [comment]
Various additional tools

**Comment by dhamaniasad** [comment]
Can you open 1 PR per link please?

**Comment by cbbrowne** [comment]
Split set of new links into separate commits, as per the recommended policy.

**Comment by dhamaniasad** [comment]
We require one pull request per item, so that each item can be judged individually. With 1 commit per item but a single PR, I either approve all the 6 items or reject them all.

**Comment by dhamaniasad** [comment]
I'm going to close this PR, and I recommend you open 1 PR per item you would like to see added in the list.

**Pull request closed without merging**
