### PR TITLE
Add postgres-checkup by Postgres.ai team

### PR DESCRIPTION
**Pull request by binakot**
Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244/files

### CODE REVIEW

**Comment by binakot** [comment]
@dhamaniasad Hello. Will you merge this PR and what's wrong with travis ci?

**Comment by dhamaniasad** [comment]
Hi @binakot,

Have you used this tool? If yes, can you provide a sample of the output generated by it?

**Comment by binakot** [comment]
> Hi @binakot,
> 
> Have you used this tool? If yes, can you provide a sample of the output generated by it?

Sure! This is the repo with examples https://gitlab.com/postgres-ai/checkup-demo
And here is full report example https://gitlab.com/postgres-ai/checkup-demo/blob/master/e1_full_report.md

**Comment by binakot** [comment]
> > Hi @binakot,
> > Have you used this tool? If yes, can you provide a sample of the output generated by it?
> 
> Sure! This is the repo with examples https://gitlab.com/postgres-ai/checkup-demo
> And here is full report example https://gitlab.com/postgres-ai/checkup-demo/blob/master/e1_full_report.md
> 
> I'm using this tool in my prod env. It's great!

Is it enough, @dhamaniasad?

**Comment by binakot** [comment]
Any updates? @dhamaniasad

**Comment by dhamaniasad** [comment]
Thank you @binakot

**Pull request merged**
