### PR TITLE
Add an awesome badge.

### PR DESCRIPTION
**Pull request by pmatseykanets**

### CODE REVIEW

**Comment by dhamaniasad** [comment]
https://github.com/dhamaniasad/awesome-postgres/issues/111

**Comment by dhamaniasad** [comment]
@pmatseykanets Unless you have any points to add as to why this list will be benefitting from the addition of the badge, I will go ahead and close this issue.

**Comment by pmatseykanets** [comment]
@dhamaniasad IMHO:
1. The list is **awesome** and deserve an awesome badge :) 
2. Don't get me wrong but the argument that the badge distracts people personally feels kind of silly and having nothing to do with the reality. Badges including this one are all over the repos and never stand on the way of the content and great software.
3. Having a badge gets the list added to the list of awesome lists (regardless of how you feel about it's author) to get a better representation, reach and publicity for PostgreSQL and this list they deserve.

But than again it's up to you. If you feel like non-compliance is more important than reaching more people with a great info about arguably the best open-source database than sure close it.

In any case thanks for your time and consideration and of course for the list itself.

**Comment by dhamaniasad** [comment]
I personally have nothing against https://github.com/sindresorhus/awesome, I just feel like there's quite a lot of guidelines to be followed for inclusion which could hinder lists that feel the need to make some changes that suit them better but are against those guidelines. But a lot of people seem to feel that the badge is going to be mutually beneficial for both the projects, so I shall gladly let go of my own hesitation, and I'll merge this pull request :).

**Comment by dhamaniasad** [comment]
I'll just include @lohfu, @cbbrowne, and @ghost here, as I am sure they will be glad to see this change.

**Comment by sindresorhus** [comment]
@dhamaniasad Everything is up for discussion. Assumptions are dangerous 😉

**Pull request merged**
