### PR TITLE
add new category: Videos

### PR DESCRIPTION
**Pull request by ImreSamu**
I have created a new "Videos" section with some proposals.
( suggested by: https://github.com/sindresorhus/awesome/pull/808  _"Could use a Videos section. Lots of great videos about PostgreSQL "_)

Because lot of great PostgreSQL videos ...  I have selected some ( popular) youtube channels.

I am not sure this is a best solution. So no problem if this is not accepted.

For example MySQL has a  Resources section.  https://github.com/shlomi-noach/awesome-mysql/blob/gh-pages/index.md
* Resources
  *  Conferences
  *  E-Books
  *  Media
  *  Newsletters

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Is linking to channels the best way forward? Or should we go with links to individual videos that we know to be awesome instead? I'd definitely remove the Postgres youtube topic, there's no gauge of any kind to judge on there.

**Comment by ImreSamu** [comment]
>Is linking to channels the best way forward? 

I don't know ...  

There are lot of greet videos , so maybe we should create a separated  **"awesome-postgres-videos"** list or restrict videos.

> I'd definitely remove the Postgres youtube topic,

I have removed 2 entries.  

// No problem if we wait to find a better solution  or  not merging this pull request.

**Comment by dhamaniasad** [comment]
> There are lot of greet videos , so maybe we should create a separated "awesome-postgres-videos" list or restrict videos.

We can create a Videos.md file if we have a relatively large number of individual videos. 
I've always liked the Resources section of the awesome-python list. 
https://github.com/vinta/awesome-python/tree/f54be88abad8306b388c6ff3c8c71843707636ce#resources

On second thought, since we already link blogs too, YouTube channels shouldn't be an issue. I'll go through the channels you've linked, and we can decide which ones are fit for the list. If you know any specific awesome videos too, we can add them to the list, that's not at all a problem :).

**Comment by ImreSamu** [comment]
> I'll go through the channels you've linked, and we can decide which ones are fit for the list.

Ok

**Comment by dhamaniasad** [comment]
Thanks, lets merge this! Sorry for the delay.

**Pull request merged**
