### PR TITLE
sqitch tool

### PR DESCRIPTION
**Pull request by cbbrowne**

### CODE REVIEW

**Comment by NikolayS** [comment]
sqitch tool is awesome, should be definitely in the list

**Comment by dhamaniasad** [comment]
@NikolayS PRs are welcome for the suggested section :)

**Comment by cbbrowne** [comment]
I suggest accepting the pull requests that are agreed to be awesome, then we could see about reorganizing them.  There are a LOT of outstanding pull requests at the moment, and it takes an irritating amount of effort to spawn branches just to separate out items into separate pull requests.

Indeed, I'm not sure it's possible to do this without foregoing the "one item per pull request" dictum.

**Comment by dhamaniasad** [comment]
Thanks, merged! Sorry for the _really long_ delay.

**Pull request merged**
